version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    expose:
      - "5433"
    env_file:
      - ./env.dev.psql
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./psql_start:/docker-entrypoint-initdb.d
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    restart: always
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    build:
      dockerfile: build/Dockerfile.app
    ports:
      - "8080:5000"
    env_file:
      - ./env.dev.app
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./src:/app

networks:
  rede_ada_projeto_final:
