version: '3.8'

services:
  psql_projeto_final:
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    expose:
      - "5432"
    env_file:
      - ./env.dev.psql
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./psql_start:/docker-entrypoint-initdb.d
      - ./volumes/postgres:/var/lib/postgresql/data
    

  app_projeto_final:
    platform: linux/amd64
    build: 
      dockerfile: build/Dockerfile.app
    image: projetofinal:latest
    depends_on:
      psql_projeto_final:
        condition: service_healthy
    ports:
      - "8080:5000"
    env_file:
      - ./env.dev.app
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./src:/app

networks:
  rede_ada_projeto_final: